# This Python script, SConscript, invoked by the SConscript in the upper directory,
# 1. builds campaign static library

Import("env")

campaignSrcFiles = [
    "EventCoordinator.cpp",
    "InterventionFactory.cpp",
    "InterventionName.cpp",
    "Interventions.cpp",
    "NodeSetAll.cpp",
    "NodeSetNodeList.cpp",
    "NodeSetFactory.cpp",
    "stdafx.cpp",
    ]

campaignLib = env.StaticLibrary('campaign', campaignSrcFiles)
