# -*- mode: python; -*-
# This Python script, SConscript, invoked by the SConscript in the upper directory,
#
# 1. builds sqlite static library

Import("env")

sqliteSrcFiles = ["sqlite3.c"]

sqliteLib = env.StaticLibrary('libsqlite', sqliteSrcFiles)
