# This Python script, SConscript, invoked by the SConscript in the upper directory,
# 1. builds customReport static library

Import("env")


generic_cpp = [
    "ReportDrugStatus.cpp",
    "ReportInfectionDuration.cpp",
    "ReportHumanMigrationTracking.cpp",
    "ReportPluginAgeAtInfectionHistogram.cpp",
    "ReportPluginAgeAtInfection.cpp",
    "ReportEventCounter.cpp",
    "ReportNodeDemographics.cpp",
    "ReportSimulationStats.cpp",
    "SqlReport.cpp",
]

vector_cpp = [
    "ReportVectorGenetics.cpp",
    "VectorHabitatReport.cpp",
    "ReportVectorMigration.cpp",
    "ReportVectorStats.cpp",
    "ReportMicrosporidia.cpp",
]

malaria_cpp = [
    "MalariaImmunityReport.cpp",
    "ReportAntibodies.cpp",
    "MalariaPatientJSONReport.cpp",
    "SqlReportMalaria.cpp",
    "SqlReportMalariaGenetics.cpp",
    "MalariaSummaryReport.cpp",
    "MalariaSurveyJSONAnalyzer.cpp",
    "ReportFpgNewInfections.cpp",
    "ReportFpgOutputForObservationalModel.cpp",
    "ReportInfectionStatsMalaria.cpp",
    "ReportMalariaFiltered.cpp",
    "ReportMalariaFilteredIntraHost.cpp",
    "ReportSimpleMalariaTransmission.cpp",
    "ReportInterventionPopAvg.cpp",
    "SpatialReportMalariaFiltered.cpp",
    "ReportNodeDemographicsMalaria.cpp",
    "ReportNodeDemographicsMalariaGenetics.cpp",
    "ReportVectorStatsMalariaGenetics.cpp",
    "ReportVectorGeneticsMalariaGenetics.cpp",
]

sti_cpp = [
    "ReportPfaQueues.cpp",
    "ReportRelationshipCensus.cpp",
    "ReportRelationshipMigrationTracking.cpp",
]

hiv_cpp = [
]

disease = "ALL"
if 'Disease' in env and len(env['Disease']) > 0:
    disease = env["Disease"]


reporters_cpp = [
    "stdafx.cpp"
]

reporters_cpp = reporters_cpp + generic_cpp
 
if( (disease == "ALL") or (disease == "Vector") or (disease == "Malaria") ):
    reporters_cpp = reporters_cpp + vector_cpp

if( (disease == "ALL") or (disease == "Malaria") ):
    reporters_cpp = reporters_cpp + malaria_cpp

if( (disease == "ALL") or (disease == "STI") or (disease == "HIV") ):
    reporters_cpp = reporters_cpp + sti_cpp

if( (disease == "ALL") or (disease == "HIV") ):
    reporters_cpp = reporters_cpp + hiv_cpp

reporters_lib = env.StaticLibrary('reporters', reporters_cpp)
