# This Python script, SConscript, invoked by the SConscript in the upper directory,
# 1. builds baseReportlib static library

Import("env")

reportSrcFiles = [
    "BaseChannelReport.cpp",
    "BaseEventReport.cpp",
    "BaseEventReportIntervalOutput.cpp",
    "BaseTextReport.cpp",
    "BaseTextReportEvents.cpp",
    "BinnedReport.cpp",
    "ChannelDataMap.cpp",
    "ReportFilter.cpp",
    "ReportFilterRelationship.cpp",
    "ReportUtilities.cpp"
]

if ('Disease' in env) and ((env['Disease'] == 'Malaria') or (env['Disease'] == '')):
    reportSrcFiles.append( "ReportUtilitiesMalaria.cpp" )

reportLib = env.StaticLibrary('baseReportLib', reportSrcFiles)
