name: Build COMMON and publish to PyPI

on:
  workflow_dispatch:

jobs:
  build:
    name: Build executable
    runs-on: ubuntu-latest
    env:
      USER: GHA-Workflow
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check python; build executable; strip symbols; make schema; extract version
        uses: addnab/docker-run-action@v3
        with:
          image: docker-production.packages.idmod.org:443/idm/dtk-centos-buildenv:3.0
          options: --mount type=bind,src=/home/runner/work/EMOD/EMOD,dst=/EMOD
          run: |
            python3 --version
            python3 -m pip list
            cd EMOD
            scons --Release --jobs=4 --Disease=Generic
            strip build/x64/Release/Eradication/Eradication
            ./build/x64/Release/Eradication/Eradication --get-schema --schema-path schema.json
            grep DTK_Version schema.json | sed 's/[^0-9.]//g' > version
      - name: Archive executable
        uses: actions/upload-artifact@v4
        with:
          name: Eradication
          path: ./build/x64/Release/Eradication/Eradication
      - name: Archive schema
        uses: actions/upload-artifact@v4
        with:
          name: schema.json
          path: schema.json
      - name: Archive version
        uses: actions/upload-artifact@v4
        with:
          name: version
          path: version

  publish:
    name: Publish distribution to PyPI
    runs-on: ubuntu-latest
    needs:
      - build
    environment:
      name: pypi
      url: https://pypi.org/project/emod-common
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Download executable
        uses: actions/download-artifact@v5
        with:
          name: Eradication
          path: pypi_common/src/eradication_dir
      - name: Download schema
        uses: actions/download-artifact@v5
        with:
          name: schema.json
          path: pypi_common/src/schema_dir
      - name: Download version
        uses: actions/download-artifact@v5
        with:
          name: version
          path: pypi_common/src/version_dir
      - name: Prep files
        run: |
          cd pypi_common
          cd src
          mv     version_dir/version           version
          zip -j emod_common/Eradication.zip   eradication_dir/Eradication
          zip -j emod_common/schema.zip        schema_dir/schema.json
          rm -r  version_dir
          rm -r  eradication_dir
          rm -r  schema_dir
      - name: Build PyPI distribution
        run: |
          python3 -m pip install build
          cd pypi_common
          python3 -m build
      - name: Upload files to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          packages-dir: pypi_common/dist
