name: Build only

on:
  # Allows manual run from the Actions tab
  workflow_dispatch:
    inputs:
      disease_type:
        description: 'Disease type in SCons build'
        type: choice
        options:
          - 'All'
          - 'Generic'
          - 'HIV'
          - 'Malaria'

jobs:
  build_artifacts:
    name: Build and create artifacts
    uses: ./.github/workflows/build_archive.yml
    with:
      disease_type: ${{ inputs.disease_type }}
